package car;
//import dependencies
import javax.swing.JOptionPane;
//declare class
class CarTest {
	//declare main method
	public static void main(String[] args) {
		//gather inputs
		String make = JOptionPane.showInputDialog("Input Make");
		String model = JOptionPane.showInputDialog("Input Model");
		String year = JOptionPane.showInputDialog("Input Year");
		String price = JOptionPane.showInputDialog("Input Price");
		//construct car object
		Car car1 = new Car(make , model, year, price);
		//output too string generated by car class
		System.out.println(car1);
	}

}
